### ISSUE TITLE
Tls

### ISSUE THREAD

**Issue by waynespace** [FunctionClub/v2ray.fun#1]
能用这样的神器是我等小白来说真是太方便了，谢谢作者的辛勤劳动，请问将来会支持ws+Nginx+TLS吗，这是一个很好的方案吧！

**Comment by YLWS-4617** [comment]
我也在想，只是最近时间比较紧，没太多时间开发这个。有空的时候我会专门找一天来实现SSL功能的。Nginx这个我没法集成，需要各位自己安装。下一次更新成 SSL +WS这个功能。
