### ISSUE TITLE
建议：增加功能

### ISSUE THREAD

**Issue by Vywh** [FunctionClub/v2ray.fun#10]
每次一个端口的配置不够用，有没有计划支持多个端口，每个端口分别配置UUID等。
还有会不会支持直接自己定义Http header？

**Comment by Vywh** [comment]
再问一下使用v2ray.fun更改config.json之后怎么添加新的端口？

**Comment by sw1999** [comment]
感谢制作这个脚本，方便新手。bwh装centos7没有开启防火墙，会一直提示：/etc/init.d/v2ray: line 94: killall: command not found。再提一个建议：希望能增加双模式运行，主端口vmess模式，副端口ss模式，这样不支持v2ray的路由或者手机也可以使用ss方式。

**Comment by zyh001** [comment]
@Vywh 多用户版本正在考虑中
目前脚本能做到的东西很有限，请谅解
