### ISSUE TITLE
重启后无法启动

### ISSUE THREAD

**Issue by AlphaDoglas** [FunctionClub/V2ray.Fun#12]
重启后无法启动
错误提示为
v2ray.fun: ERROR (abnormal termination)

**Comment by Mr-Sheep** [comment]
重启后需要重启下服务
具体位置为 /usr/local/V2ray.Fun 下的start.sh
可以用nohup执行，具体命令如下
cd /usr/local/V2ray.Fun
nohup ./start.sh &
或者可以直接添加至开机启动中
