### ISSUE TITLE
如何更新脚本？

### ISSUE THREAD

**Issue by LennoC** [FunctionClub/v2ray.fun#12]
直接下载install.sh覆盖的话，每次bash打开都会重新下载安装一遍v2ray。提供个只更新脚本的选项会比较好一点吧？

**Comment by zyh001** [comment]
@LennoC 你好，目前采用这种方式的好处是可以保证v2ray的主程序随时处于最新状态。

**Comment by LennoC** [comment]
@zyh001 目前已知最大的问题，这样会导致每次更新脚本都会把服务端重置。于是客户端不得不跟着变化或重新设置服务端。官方go.sh/install.sh只更新主程序并不会覆盖json设置。望改进。 (开发者加油，感谢

**Comment by YLWS-4617** [comment]
您好，已经写好了更新脚本，现在运行更新脚本不会覆盖原有的配置端文件。具体命令在 Readme 里面。
