### ISSUE TITLE
关于TLS

### ISSUE THREAD

**Issue by LennoC** [FunctionClub/v2ray.fun#15]
偶然发现域名变成https了，证书是Let's Encrypt的。最近的操作就是v2ray.fun了。所以，v2ray.fun默认加入tls证书？
我用的是caddy，请问应该怎么操作让网站不强制跳转https？我需要用frp+aria2+ariang，这导致我的aria2也必须走https流量。
（顺便，最近在研究frp内网穿透，一直失败。不清楚是否和https相关，若有人解答，感激不尽。

**Comment by LennoC** [comment]
另外，相关功能还是建议做成可选项。

**Comment by YLWS-4617** [comment]
首先， Caddy 是自动签发 Let 的HTTPS 证书，与本脚本无关。具体操作请阅读 Caddy 的官方指南。

其次，请解释下 “相关功能还是建议做成可选项” 这句话的意思。

**Comment by LennoC** [comment]
@YLWS-4617 不好意思，我也是后来才查到是Caddy自动签发的HTTPS证书。真十分不好意思。
因为在用v2ray.fun之前我的域名一直是http的，当时突然就变成https了，我以为是v2ray.fun的功能，希望将此功能做成可选项。这是个误会。再次道歉。可以close issue了。
ps. 在运行一次v2ray.fun的upgrade.sh我的https又不能用了，真·TM·神奇。。我都不知道是哪里的问题了。。。
