### ISSUE TITLE
小白鼠 汇报一下安装测试

### ISSUE THREAD

**Issue by KyonCN** [FunctionClub/V2ray.Fun#16]
Debian 9    无法安装成功  pip报错  v2ray命令执行失败
Ubuntu 14  无法安装成功
Ubuntu 16  安装成功 服务无法启动
centos 7    安装成功  服务一切正常  但是与bifrostv客户端不兼容

**Comment by watanaberyunosuke** [comment]
Ubuntu 18 successfully installed, can not launch panel

**Comment by Min9X1n** [comment]
您好，Debian9和Ubuntu已经修复，感谢
