### ISSUE TITLE
ubuntu14 重启后面板失效

### ISSUE THREAD

**Issue by ntgeralt** [FunctionClub/V2ray.Fun#17]
全新纯净ubuntu14，apt-get update后安装面板，reboot后无法进入，提示：
v2ray.fun: ERROR (not running)
v2ray.fun: ERROR (abnormal termination)

请教如何解决。。

下面命令行

root@ubuntu14:~# v2ray
欢迎使用 V2ray.Fun 面板 ---- By 雨落无声

当前面板用户名：admin
当前面板密码：admin
当前面板监听端口：5000
请输入数字选择功能：

1. 启动面板
2. 停止面板
3. 重启面板
4. 设置面板用户名和密码
5. 设置面板SSL
6. 设置面板端口

请选择：3
v2ray.fun: ERROR (not running)
v2ray.fun: ERROR (abnormal termination)
重启成功!
root@ubuntu14:~#

**Comment by zyh001** [comment]
@ntgeralt 请参考 #12 解决方案。感谢您对项目的支持
