### ISSUE TITLE
请不要从member.3322.org获取IP地址

### ISSUE THREAD

**Issue by wayne630** [FunctionClub/V2ray.Fun#18]
请从境外服务器获取服务器的IP地址，否则被wall的服务器运行此脚本就会因为无法获取服务器的公网IP而卡很久，进而安装好后要手动配置config，面板才会显示服务器IP。

**Comment by zyh001** [comment]
@wayne630 您好，IP获取地址已更改为ifconfig.me，感谢您对本项目的支持😁

**Comment by zyh001** [comment]
@wayne630 不好意思，已经修复！
之前眼瞎，没看清😅
