### ISSUE TITLE
已有caddy申请的LETS证书，可以让TLS使用已有的证书

### ISSUE THREAD

**Issue by LennoC** [FunctionClub/v2ray.fun#19]
1. 已有caddy并自动获取了LETS的证书。
v2ray.fun的开启TLS功能会重新获取并存储在/root/.acme.sh目录。
可以修改为使用caddy使用的证书吗？或者增加自定义SSL证书路径的功能。
2. 通过v2ray.fun配置使用WS+TLS+CADDY，总是会失败（可能是我自己原因）。建议增加一键配置功能+guider。

**Comment by YLWS-4617** [comment]
1.因为针对最初级的小白设定，是只需要一键，就能配置好SSL证书，所以加入手动选择证书目录，可能会使得操作变难，不过，如果不是最初级小白，自己就可以改config.json里的证书路径。

2.分流之类的操作是属于比较高级一些的玩法了，我希望用户能自己研究。脚本的初衷只是在V2ray的基础上进行配置，简化v2ray本身的配置部分。Nginx分流，Caddy之类的，我暂时没打算做。

PS: 我也想加入很多功能，但是很多人都有不同的看法，有人认为稳定能用就好，有人却一直在提议加入新功能，有的用户水平及其小白，脚本写复杂了就不会用，有的用户知道整个配置文件的写法，只是想偷个懒用脚本，希望脚本能加入新功能。 我很想在这之间做一个平衡，所以，我的选择是保持现在这样就行了。功能如果太复杂了，反而会显得很累赘。

**Comment by LennoC** [comment]
@YLWS-4617 
1. 好的，明白。借楼顺便问一句，caddy获取了LETS证书，v2ray.fun又获取了一次证书，会导致证书冲突吗？我在WS+TLS+CADDY的过程就一直报错误【 Proxy|VMess|Outbound: failed to find an available destination > Retry: [Transport|Internet|WebSocket: failed to dial WebSocket > Transport|Internet|WebSocket: failed to dial to (wss://ip add/ws):  > x509: cannot validate certificate for ip add because it doesn't contain any IP SANs] > Retry: all retry attempts failed】。
2. 功能的选择其实可以考虑增加初级和高级的区别，在原来的1-4加个5[高级功能]。初级情况下就是原来的功能，进入高级选项后才有更细化或者复杂的功能，例如分流什么的。
3.我也算小白，只是略懂一些json和简单配置，属于看得懂教程，但不明白原理的。之所以要考虑WS+TLS+CADDY/NGINX是因为最近网络封锁加强，我所在的深圳天威宽带直接上半白名单了，非国内的域名/服务器连不上或间歇性或封端口。我自己的域名只能连上HTTPS的443了，所以才要考虑分流。
最后，感谢解答。

**Comment by KiritoMiao** [comment]
@LennoC 通过某种开关启用高级功能（请连续点击五次版本号）

**Comment by YLWS-4617** [comment]
1. 证书不会冲突，是两个独立的文件。这个错误，建议检查下Caddy配置，应该是ws路径之类的问题。
2.了解，以后考虑加上去。
