### ISSUE TITLE
ubuntu16.04安装面板后无法启动

### ISSUE THREAD

**Issue by a1768623020** [FunctionClub/V2ray.Fun#19]
v2ray.fun: ERROR (spawn error)
启动成功!
浏览器无法访问。。

**Comment by uhlhosting** [comment]
v2ray.fun: ERROR (not running)
停止成功！
root@sentry:/usr/local/bin# v2ray
欢迎使用 V2ray.Fun 面板 ---- By 雨落无声

当前面板用户名：vray
当前面板密码：Vodka33cl!!
当前面板监听端口：7777
请输入数字选择功能：

1. 启动面板
2. 停止面板
3. 重启面板
4. 设置面板用户名和密码
5. 设置面板SSL
6. 设置面板端口

请选择：1
v2ray.fun: ERROR (spawn error)
启动成功!

**Comment by zhangzheng7856** [comment]
debian9 
请选择：1
v2ray.fun: ERROR (spawn error)
启动成功!
root@vultr:~#

**Comment by Min9X1n** [comment]
您好，现在应该可以了，我修改了了脚本，代码已经合并了 @zhangzheng7856 @a1768623020 @uhlhosting

**Comment by wenchengxucool** [comment]
@zhangzheng7856 你的解决了吗？什么情况？Debian 8.3.0-7的vultr求问
