### ISSUE TITLE
挺好用的哈，有个小小的巨型建议

### ISSUE THREAD

**Issue by cheapssr** [FunctionClub/v2ray.fun#2]
直接搞个销售管理系统出来。。v2ray就普及了

**Comment by cheapssr** [comment]
酸酸乳就是这么普及下来的

**Comment by YLWS-4617** [comment]
这个道理非常明显。
官方那里现在有个V2ray的多用户面板：https://github.com/v2ray/v2ray-Panel
但是因为现在V2ray的客户端还不是很完善，就算有了销售系统，也是很难普及下来。还要等待官方开发。
