### ISSUE TITLE
经我这样改良，这些Issues都可以close了

### ISSUE THREAD

**Issue by wayne630** [FunctionClub/V2ray.Fun#20]
版主大人，昨天我研究了半天你的脚本，只要你按我这样做，目前存在的Issues都可以close了。

1、不是所有服务器安装系统时都有pip命令，因此，建议在脚本加入如下安装pip命令
#Install git
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python get-pip.py
rm -rf get-pip.py
（加在#Install acme.sh之前）

2、最好在脚本中把/etc/v2ray/config.json权限设置成777，否则会有一些奇葩问题发生，例如面板改了设置，实际上并没有按照面板设置修改
chmod 777 /etc/v2ray/config.json

3、重要！开机时一定要启动supervisord服务，否则通过v2ray命令无法启动面板。事实上，在脚本加入如下命令，在服务器启动后已可自动启动面板
echo "supervisord -c /etc/supervisor/supervisord.conf">>/etc/rc.d/rc.local
chmod +x /etc/rc.d/rc.local

4、app.py以及Config_Generator.py的所有open(...)地方，文件名全部应该为绝对路径，否则服务器重启后会出现修改设置无法生效的奇葩bug
例如：app.py第8行：panel_config_file = open("panel.config","r")
应为：panel_config_file = open("/usr/local/V2ray.Fun/panel.config","r")

5、Config_Generator.py第9行替换掉URL为http://ifconfig.me，不要用member.3322.org获取服务器公网IP，否则你懂的……

我用ESXi搭CentOS7.3跑了一遍，反复重启几次面板均能自动启动，修改设置也生效，基本完美了。

**Comment by zyh001** [comment]
@wayne630  您如果对有好的建议，欢迎您直接提交pr

**Comment by zyh001** [comment]
改良更改已经提交，感谢您的支持
