### ISSUE TITLE
如果可以支持复制地址或者扫描二维码导入配置文件就更棒了

### ISSUE THREAD

**Issue by anotaku** [FunctionClub/v2ray.fun#20]
脚本特别好用

**Comment by YLWS-4617** [comment]
目前正在做这个部分，准备使用ShadowRay的 vmess:// 链接配置规则来生成 二维码。预计下下个星期可以发布。谢谢支持。

**Comment by afboyxiyang** [comment]
赞，以后直接扫描就行了！
就是显示出来后，直接在屏幕上显示就更好了，如果不行，就是生成的二维码可以跟配置文件一起直接下载到电脑就好了
