### ISSUE TITLE
tls证书

### ISSUE THREAD

**Issue by updater1234** [FunctionClub/v2ray.fun#21]
你好，请问一下。在开启tls的证书时，能添加一个是选择rsa还是ecc证书的功能吗？因为ecc的安全性比rsa好一。

**Comment by updater1234** [comment]
还有从配置文件上看，怎么是默认启动可http伪装？

**Comment by YLWS-4617** [comment]
1.TLS证书已全部改成 ECC 证书，谢谢反馈。目前看来ECC证书确实比较先进，我就直接改成ECC了。让小白用户选择使用RSA或者ECC还是比较困难的。
2.默认HTTP伪装是我自己在国内测试的时候，感觉速度比较好，大部分地区都能直接使用，所以默认就设置成http伪装了。反正用户安装完成后也能自有修改，没什么问题。

**Comment by updater1234** [comment]
那请问我怎么吊销原来的证书？

**Comment by zyh001** [comment]
@updater1234 重新安装，原证书就失效了

**Comment by updater1234** [comment]
请问以后可以添加国内直连的功能吗？

**Comment by YLWS-4617** [comment]
脚本只满足最基本的上网需要，更高级的功能，请自己研究。

**Comment by YLWS-4617** [comment]
现在就是国内直连啊。。。如果说有部分IP端没有在直连段配置里面，请自己添加。
