### ISSUE TITLE
希望可以增加国内VPS中转功能

### ISSUE THREAD

**Issue by liuminglm** [FunctionClub/v2ray.fun#22]
家里联通的宽带，买了个CN2的vps，延迟太高，希望买个阿里或者腾讯云进行中转，希望可以增加这个功能

**Comment by zyh001** [comment]
@liuminglm 你好，脚本暂时不会支持该功能，你需要自己修改配置文件，关于转发配置请参考[V2ray的官方文档](https://www.v2ray.com/chapter_05/00_config/07_vps_relay.html)，谢谢支持

**Comment by joeguo** [comment]
官方文档出错，
提示Main: failed to read config file: /etc/v2ray/config.json > Ext|Tools|Conf|Serial: failed to read config file > invalid  character ':' after array element

检查，也没有发现异常；只是这个json文档不对；请检查，谢谢

**Comment by zyh001** [comment]
@joeguo 请贴出你的配置文件

**Comment by liuminglm** [comment]
@joeguo @zyh001 我是完全copy官网的配置文件进行配置的，就是把id，address这些改成自己的，也是这些错误提示，我现在是在vps开两个v2ray，一个不走国外的国内直连，一个完全走国外vps，然后手机电脑，按需求配置（滑稽..）

**Comment by joeguo** [comment]
我是直接拷贝官网的json配置文件，不做任何修改的情况下，报上面的错误；修改uid,address,port之后也是报错。

**Comment by liuminglm** [comment]
@zyh001 @joeguo 贴一个我目前使用的配置，这个不能够国内国外自动分流，只能全部转发
{
 "outbound": {
  "streamSettings": {
   "security": "", 
   "tcpSettings": null, 
   "network": "ws", 
   "kcpSettings": null, 
   "wsSettings": {
    "path": "", 
    "connectionReuse": true
   }
  }, 
  "tag": "agentout", 
  "protocol": "vmess", 
  "mux": {
   "enabled": true
  }, 
  "settings": {
   "vnext": [
    {
     "users": [
      {
       "alterId": 100, 
       "security": "aes-128-gcm", 
       "id": "XXXXXXXXXXXXX"
      }
     ], 
     "port": 80, 
     "address": "XXXXXXXXX"
    }
   ]
  }
 }, 
 "log": {
  "access": "", 
  "loglevel": "info", 
  "error": ""
 }, 
 "outboundDetour": [
  {
   "tag": "direct", 
   "protocol": "freedom", 
   "settings": {
    "response": null
   }
  }, 
  {
   "tag": "blockout", 
   "protocol": "blackhole", 
   "settings": {
    "response": {
     "type": "http"
    }
   }
  }
 ], 
 "inbound": {
  "streamSettings": null, 
  "settings": {
   "ip": "127.0.0.1", 
   "udp": true, 
   "clients": null, 
   "auth": "noauth"
  }, 
  "protocol": "socks", 
  "port": 1030, 
  "listen": "0.0.0.0"
 }, 
 "inboundDetour": null, 
 "routing": {
  "settings": {
   "rules": [
    {
     "ip": [
      "0.0.0.0/8", 
      "10.0.0.0/8", 
      "100.64.0.0/10", 
      "127.0.0.0/8", 
      "169.254.0.0/16", 
      "172.16.0.0/12", 
      "192.0.0.0/24", 
      "192.0.2.0/24", 
      "192.168.0.0/16", 
      "198.18.0.0/15", 
      "198.51.100.0/24", 
      "203.0.113.0/24", 
      "::1/128", 
      "fc00::/7", 
      "fe80::/10"
     ], 
     "domain": null, 
     "type": "field", 
     "port": null, 
     "outboundTag": "direct"
    }
   ], 
   "domainStrategy": "IPIfNonMatch"
  }, 
  "strategy": "rules"
 }, 
 "dns": {
  "servers": [
   "8.8.8.8", 
   "8.8.4.4", 
   "localhost"
  ]
 }
}

**Comment by joeguo** [comment]
@liuminglm 在国内vps上搭建一个，就想着自动分流不是?

**Comment by liuminglm** [comment]
@joeguo 我目前很需要自动分流，公司无线网不知道怎么了github上不去，只能通过阿里云来中转，如果只是想中转，用我的这个配置足够了，不用中转的，你终端直接设置直连就好了

**Comment by zyh001** [comment]
@liuminglm 我看了一下配置，没发现什么明显的错误，建议到V2Ray的GitHub主页提交issue

**Comment by KiritoMiao** [comment]
@zyh001 用域名白名单啊
