### ISSUE TITLE
更新后错误

### ISSUE THREAD

**Issue by wonghuqiang** [FunctionClub/v2ray.fun#26]
[Info]App|Proxyman|Inbound: connection ends > Proxy|Socks: connection ends > context canceled

**Comment by YLWS-4617** [comment]
更新后请重新下载一遍客户端配置文件，谢谢！如还有问题，请再开Issue

**Comment by FDKPIBC** [comment]
@zyh001 还是无法访问

**Comment by Punizione** [comment]
@FDKPIBC 看一下你的` /usr/local/V2ray.Fun/` 目录有没有 `panel.config`这个文件，然后执行一下 `ll` 命令，截个图上来看看
