### ISSUE TITLE
重启VPS后面板不能正常启动,v2ray正常启动.

### ISSUE THREAD

**Issue by sanwzzz** [FunctionClub/V2ray.Fun#26]
root@digitalocean:~# v2ray
欢迎使用 V2ray.Fun 面板 ---- By 雨落无声

当前面板用户名：xxx
当前面板密码：xxx
当前面板监听端口：xxx
请输入数字选择功能：

1. 启动面板
2. 停止面板
3. 重启面板
4. 设置面板用户名和密码
5. 设置面板SSL
6. 设置面板端口

请选择：1
v2ray.fun: ERROR (abnormal termination)
启动成功!

**Comment by Min9X1n** [comment]
请问你的系统是？

**Comment by sanwzzz** [comment]
Debian 8.10 x64

**Comment by Punizione** [comment]
@sanwzzz 
试试  `python /usr/local/V2ray.Fun/app.py` 看看怎么样

**Comment by FDKPIBC** [comment]
@Punizione 
`
Traceback (most recent call last):
  File "/usr/local/V2ray.Fun/app.py", line 3, in <module>
    from flask import Flask,render_template,request
ImportError: No module named flask
`

**Comment by zyh001** [comment]
@FDKPIBC 请尝试执行以下命令，再重复上述操作：
```
pip install --upgrade pip
pip install flask requests urllib3 Flask-BasicAuth supervisor Jinja2 requests six wheel
pip install pyOpenSSL
```

**Comment by FDKPIBC** [comment]
@zyh001 
`Traceback (most recent call last):
  File "/usr/local/V2ray.Fun/app.py", line 8, in <module>
    panel_config_file = open("panel.config","r")
IOError: [Errno 2] No such file or directory: 'panel.config'`

**Comment by FDKPIBC** [comment]
@zyh001 v2ray命令下的启动面板命令提示成功启动面板了,但是无法访问面板

**Comment by zyh001** [comment]
@FDKPIBC 重新跑一遍安装脚本

**Comment by FDKPIBC** [comment]
@Punizione 重启了一次,正常了...

**Comment by Min9X1n** [comment]
@zyh001 抱歉，上次改回centOS的时候pip依赖漏掉了

**Comment by sanwzzz** [comment]
@Punizione 



![20180821171117](https://user-images.githubusercontent.com/39424325/44393657-e2cb7800-a567-11e8-979e-66ab3e15e22f.png)

**Comment by Punizione** [comment]
@sanwzzz  emmm可能你需要重新跑一遍安装脚本.... 我无法确定是什么原因 你是DigitalOcean的Debian吧？明天我开台新机试试。。

**Comment by Punizione** [comment]
@sanwzzz 再跑一下一键脚本吧... 开了台机没出现你发现的问题..

**Comment by sanwzzz** [comment]
@Punizione 是DO家的,重跑一遍还是不行,重做系统又跑了一遍可以了,VPS装了宝塔并且挂了一个站

**Comment by Punizione** [comment]
@sanwzzz  
没啥问题的话就close掉吧 可能是宝塔的锅...使用纯净系统好一点
