### ISSUE TITLE
局域网网站无法访问的问题？

### ISSUE THREAD

**Issue by mrwenhui** [FunctionClub/v2ray.fun#28]
问题地址：https://github.com/v2ray/v2ray-core/issues/696

**Comment by YLWS-4617** [comment]
@mrwenhui 客户端配置文件里有一行192.168.0.0/16 表示禁止局域网访问。

**Comment by mrwenhui** [comment]
假如局域网的网站为  192.168.50.50 匹配到指一条， 直接按direct 执行freedom 策略 没有任何问题啊？

**Comment by YLWS-4617** [comment]
那我不清楚了 =.=
