### ISSUE TITLE
不是纯净的新系统，安装后5000端口无法访问

### ISSUE THREAD

**Issue by leepoi** [FunctionClub/V2ray.Fun#3]
Ubuntu 16.04 LTS

没办法，vps之前运行着ss，按照步骤安装完毕，发现v2ray主进程已经运行，但lsof -i:5000  端口没有监听程序。酷炫的web控制台看不到，安装的时候没有报错，也没找到安装日志，很无奈啊。

难道一定要用全新系统来安装？

**Comment by zyh001** [comment]
@leepoi 您好，您可以尝试使用`cd /usr/local/V2ray.Fun/ && screen -dmS Flask python app.py`命令，手动启动服务，如果还不行，请再次联系。

**Comment by onplus** [comment]
可能需要 `pip install Flask-BasicAuth`

**Comment by zyh001** [comment]
@onplus 如果采用脚本或者教程上的方法，那么Flask-BasicAuth将是已经被安装的，所以无需担心，只可能是服务未启动，手动开启就行了

**Comment by leepoi** [comment]
@onplus  谢了，真是这个原因呢。
@zyh001  最后确认了，pip install Flask-BasicAuth 后再运行就好了，我之前按照教程安装后，并未自动安装Flask-BasicAuth，导致运行失败，最后还是谢谢你做这个控制页面，别的不多说，炫酷啊！！

**Comment by parastars** [comment]
你好，用了一键脚本显示line1～9（end）怎么继续呢？
