### ISSUE TITLE
2.4.7版安装成功后提示v2ray: unrecognized service

### ISSUE THREAD

**Issue by iWynn** [FunctionClub/v2ray.fun#31]
感谢大神提供的脚本，确实很方便，但是我遇到了问题。

我有一台vps，运行的是ubuntu server 14.04版本，使用脚本一件安装后，安装成功，v2ray也能出现中文提示选项，但是使用提示启动服务或者service v2ray start后都会提示v2ray: unrecognized service，修改传输方式不会生效，无日志文件，服务列表里没有v2ray。

请问怎么办，感谢解答。

**Comment by YLWS-4617** [comment]
@iWynn 换一个系统试试看。可能是v2ray的systemd没有安装好。

**Comment by Pacio** [comment]
您好，我下载的配置文件使用的是默认的1080端口，启用v2ray程序以后提示failed to listen tcp on 1080,我手动修改为1082可以显示正常的启动，但是依然无法翻墙是什么情况，我的vps使用的是debian7 64位

**Comment by YLWS-4617** [comment]
@Pacio 1.检查是否同时开了其他代理程序，例如ssr之类的，同时监听1080会报错
2.检查自己是否把浏览器配置设置正确了，软件不是一开过来就能直接使用的。

**Comment by zyh001** [comment]
@eSouT 您好，问题已经解决，感谢您的反馈
