### ISSUE TITLE
配置都OK，但是为什么翻墙失败？

### ISSUE THREAD

**Issue by Pacio** [FunctionClub/v2ray.fun#32]
v2ray程序启动正常，但是打开要翻的网站就提示unknown socks version~~

**Comment by YLWS-4617** [comment]
@Pacio 如果是IE代理设置的话，建议把电脑上配置文件里的 socks 该出去http

**Comment by Pacio** [comment]
@YLWS-4617  thx ,修改以后可以上了~~
