### ISSUE TITLE
关于二维码的问题

### ISSUE THREAD

**Issue by InoriHimea** [FunctionClub/V2ray.Fun#37]
- 问题类型 : 
  - [x] bug反馈
  - [ ] 新功能建议
  - [ ] 其它
  
----
问题详情
----

- 操作系统: debain 9
- 内核版本: 
- Python版本: 2.7
- Bash版本: 
- 脚本版本 (或者commit号): 
 
**问题描述**

 二维码在BifrostV无法扫描，而且在页面上服务器ip为空，但是手动在客户端设置参数可以正常使用

**如何复现**

使用客户端扫描 

错误信息：
-----
```
<完整日志/报错>
```
----
**其他问题**

多用户？

**Comment by zyh001** [comment]
@InoriHimea 您好，此错误的原因是BifrostV不支持Vmess链接二维码的扫描，请反馈到其官方平台。若需要您可以导出配置文件使用。感谢您对项目的支持
