### ISSUE TITLE
这个脚本支持ssr的协议吗

### ISSUE THREAD

**Issue by xunxiangke** [FunctionClub/v2ray.fun#4]
请问这个脚本如何设置ssr？

**Comment by YLWS-4617** [comment]
V2ray自身只兼容原版SS协议，不支持SSR协议哦。
欢迎阅读V2ray官方文档： https://v2ray.com

**Comment by LennoC** [comment]
@zyh001 感谢解答。尝试中。v2ray已经放出流量统计功能了，请问有加入此功能的计划吗？

**Comment by zyh001** [comment]
@LennoC 日后的版本会加入此功能，谢谢支持
