### ISSUE TITLE
是否可与CADDY/NGINX/APACHE等一起用？

### ISSUE THREAD

**Issue by LennoC** [FunctionClub/V2ray.Fun#4]
你好，感谢开发者做出的贡献。
目前我使用的是v2ray方式是caddy+vmess+tls+websocket/h2. 其中vmess开了多条端口对应不同协议。LETS证书则是caddy自动管理的。
在这种情况下，可不可以与v2ray.fun一起合用？需要做出什么修改吗？
感谢。

**Comment by zyh001** [comment]
@LennoC 可以的，你无需对面板做出任何更改，你所要做的就是修改Apache/Nginx/Caddy的配置文件，配置反向代理，指向http://127.0.0.1:5000 （端口号需要根据实际情况修改）即可，但是如果你已经原有配置v2ray，那么不再建议你使用这个面板，该面板不支持多协议多用户
