### ISSUE TITLE
运行状态不显示服务器ip

### ISSUE THREAD

**Issue by andyliang007008** [FunctionClub/V2ray.Fun#47]
- 问题类型 : 
  - [x] bug反馈
  - [ ] 新功能建议
  - [ ] 其它
  
----
问题详情
----

- 操作系统: Debian 9 x86_64
- 内核版本: 
- Python版本: 
- Bash版本: 
- 脚本版本 (或者commit号): 
 
**问题描述**
搬瓦工vps，安装后，在打开面板运行状态上没有服务器ip地址显示
 
**如何复现**

 
错误信息：
-----
```
<完整日志/报错>
```
----
**其他问题**

**Comment by orangejx** [comment]
同样不显示服务器IP

**Comment by dingyx99** [comment]
同样不显示+1

**Comment by chorkei** [comment]
目測是因為Config_Generator的getip這個方法使用的連接失效了。
可以试试这个，https://ipapi.co/ip/

**Comment by hccgk** [comment]
> 目測是因為Config_Generator的getip這個方法使用的連接失效了。
> 可以试试这个，https://ipapi.co/ip/

请问这个方法在哪个目录的那个文件？

**Comment by yuebanquan** [comment]
同样不显示

**Comment by zyh001** [comment]
该问题目前已经得到解决！
