### ISSUE TITLE
这个脚本和安装脚本貌似有冲突

### ISSUE THREAD

**Issue by tefiszx** [FunctionClub/v2ray.fun#5]
我是先用 https://install.direct/go.sh这个脚本在vps上部署了v2ray。然后用了v2ray.fun 一键安装。v2ray.fun覆盖了vps上的配置文件。并且无法找到v2ray这个命令。是不是fun的安装脚本覆盖了官方的安装文件或者是fun的脚本与v2ray的默认文件重名了？

**Comment by tefiszx** [comment]
看了下安装和运行脚本。原来是路径的问题。已经解决了。首先感些楼主提供这个方便v2ray安装和配置的小工具。不过windows客户端V2rayN已经提供了配置文件分别导出为服务器和客户端的功能，更加的直观方便。

**Comment by zyh001** [comment]
@SmileDream 已确认，是由于代码逻辑问题所导致出现无法打开网页的问题，请手动执行`cd /usr/local/V2ray.Fun/ && screen -dmS Flask python app.py`来开启，感谢您的支持
