### ISSUE TITLE
我使用mac的terminal登陆vps,如何下载客户端配置文件？

### ISSUE THREAD

**Issue by luckypoem** [FunctionClub/v2ray.fun#6]
客户端配置文件在vps里的什么地方？
谢谢回复。

**Comment by tefiszx** [comment]
客户端文件放在当前用户的home目录下，root用户就是在/root下，文件名是config.json

**Comment by zyh001** [comment]
@luckypoem 你好，你可以在Mac的终端下面，使用scp命令将配置文件复制到本地，具体命令`scp root@yourip:/root/config.json /home/username`即可

**Comment by luckypoem** [comment]
hi.

[Info]App|Proxyman|Mux: dispatching request to udp:8.8.8.8:53
2017/10/14 17:54:24 [Info]Proxy|Socks: TCP Connect request to tcp:detectportal.firefox.com:80
2017/10/14 17:54:24 [Info]App|Router: looking up IP for tcp:detectportal.firefox.com:80
2017/10/14 17:54:24 [Info]Transport|Internet|UDP: establishing new connection for udp:8.8.8.8:53
2017/10/14 17:54:24 [Info]App|Dispatcher|Default: default route for udp:8.8.8.8:53
2017/10/14 17:54:24 [Info]App|Proxyman|Mux: dispatching request to udp:8.8.8.8:53
2017/10/14 17:54:27 [Info]Transport|Internet|UDP: establishing new connection for udp:8.8.4.4:53
2017/10/14 17:54:27 [Info]App|Dispatcher|Default: default route for udp:8.8.4.4:53
2017/10/14 17:54:27 [Info]App|Proxyman|Mux: dispatching request to udp:8.8.4.4:53
2017/10/14 17:54:29 [Info]Proxy|Socks: TCP Connect request to tcp:detectportal.firefox.com:80
2017/10/14 17:54:29 [Info]App|Router: looking up IP for tcp:detectportal.firefox.com:80
2017/10/14 17:54:29 [Info]Transport|Internet|UDP: establishing new connection for udp:8.8.8.8:53
2017/10/14 17:54:29 [Info]App|Dispatcher|Default: default route for udp:8.8.8.8:53
2017/10/14 17:54:29 [Info]App|Proxyman|Mux: dispatching request to udp:8.8.8.8:53
2017/10/14 17:54:32 [Info]Transport|Internet|UDP: establishing new connection for udp:8.8.4.4:53
2017/10/14 17:54:32 [Info]App|Dispatcher|Default: default route for udp:8.8.4.4:53
2017/10/14 17:54:32 [Info]App|Proxyman|Mux: dispatching request to udp:8.8.4.4:53
2017/10/14 17:54:33 [Info]Proxy|Socks: TCP Connect request to tcp:pn.bright.biz.st:80
2017/10/14 17:54:33 [Info]App|Router: looking up IP for tcp:pn.bright.biz.st:80
2017/10/14 17:54:33 [Info]App|Dispatcher|Default: default route for tcp:pn.bright.biz.st:80
2017/10/14 17:54:33 [Info]App|Proxyman|Mux: dispatching request to tcp:pn.bright.biz.st:80
2017/10/14 17:54:34 [Info]Proxy|Socks: TCP Connect request to tcp:detectportal.firefox.com:80
2017/10/14 17:54:34 [Info]App|Router: looking up IP for tcp:detectportal.firefox.com:80
2017/10/14 17:54:34 [Info]Transport|Internet|UDP: establishing new connection for udp:8.8.8.8:53
2017/10/14 17:54:34 [Info]App|Dispatcher|Default: default route for udp:8.8.8.8:53
2017/10/14 17:54:34 [Info]App|Proxyman|Mux: dispatching request to udp:8.8.8.8:53
2017/10/14 17:54:35 [Info]App|Dispatcher|Default: default route for tcp:detectportal.firefox.com:80
2017/10/14 17:54:35 [Info]App|Proxyman|Mux: dispatching request to tcp:detectportal.firefox.com:80
2017/10/14 17:54:37 [Info]Transport|Internet|UDP: establishing new connection for udp:8.8.4.4:53
2017/10/14 17:54:37 [Info]App|Dispatcher|Default: default route for udp:8.8.4.4:53
2017/10/14 17:54:37 [Info]App|Proxyman|Mux: dispatching request to udp:8.8.4.4:53
2017/10/14 17:54:39 [Info]Proxy|Socks: TCP Connect request to tcp:detectportal.firefox.com:80
2017/10/14 17:54:39 [Info]App|Router: looking up IP for tcp:detectportal.firefox.com:80
2017/10/14 17:54:39 [Info]App|Dispatcher|Default: default route for tcp:detectportal.firefox.com:80
2017/10/14 17:54:39 [Info]App|Proxyman|Mux: dispatching request to tcp:detectportal.firefox.com:80
2017/10/14 17:54:40 [Info]App|Dispatcher|Default: default route for tcp:detectportal.firefox.com:80
2017/10/14 17:54:40 [Info]App|Proxyman|Mux: dispatching request to tcp:detectportal.firefox.com:80
2017/10/14 17:54:42 [Info]Transport|Internet|UDP: establishing new connection for udp:8.8.4.4:53
2017/10/14 17:54:42 [Info]App|Dispatcher|Default: default route for udp:8.8.4.4:53
2017/10/14 17:54:42 [Info]App|Proxyman|Mux: dispatching request to udp:8.8.4.4:53
2017/10/14 17:54:44 [Info]Proxy|Socks: TCP Connect request to tcp:detectportal.firefox.com:80
2017/10/14 17:54:44 [Info]App|Router: looking up IP for tcp:detectportal.firefox.com:80
2017/10/14 17:54:44 [Info]App|Dispatcher|Default: default route for tcp:detectportal.firefox.com:80
2017/10/14 17:54:44 [Info]App|Proxyman|Mux: dispatching request to tcp:detectportal.firefox.com:80
2017/10/14 17:54:45 [Info]App|Dispatcher|Default: default route for tcp:detectportal.firefox.com:80
2017/10/14 17:54:45 [Info]App|Proxyman|Mux: dispatching request to tcp:detectportal.firefox.com:80
2017/10/14 17:54:50 [Info]App|Dispatcher|Default: default route for tcp:detectportal.firefox.com:80
2017/10/14 17:54:50 [Info]App|Proxyman|Mux: dispatching request to tcp:detectportal.firefox.com:80
2017/10/14 17:56:44 [Info]Proxy|VMess|Encoding: failed to read response header > read tcp 192.168.1.2:52039->my_vps_ip:1234: use of closed network connection

为何翻不了墙呢？

**Comment by zyh001** [comment]
@luckypoem 你好，从 log 看不出明显的问题，请问你在具体使用过程中观察到的现象是什么？

**Comment by luckypoem** [comment]
@zyh001 
“use of closed network connection”是提示出错了吗？网络连接被关闭？

**Comment by luckypoem** [comment]
在下载而来的config.json文件里的：
"protocol": "socks",
  "port": 1080,
  "listen": "0.0.0.0"
 } 

--------
"listen": "0.0.0.0"   是否应该改为"listen": "127.0.0.1"？

**Comment by zyh001** [comment]
@luckypoem 不必改为127.0.0.1

**Comment by YLWS-4617** [comment]
@luckypoem 请给出详细的服务端日志。
