### ISSUE TITLE
[新人一些疑惑]和v2ray官方一键安装包有冲突？应该给一些guide.

### ISSUE THREAD

**Issue by LennoC** [FunctionClub/v2ray.fun#7]
1. 已安装v2ray官方包的情况运行了v2ray.fun，好像是被直接覆盖了？ 反正原来的连不上了。
2. 应该给sh增加一些参数的。比如remove/update，现在没参数打开后直接重新覆盖安装。
3. 对应到手机端。Android可以直接导入json，ios我使用的Shadowrocket和Shadowray，在伪装方面应该如何填写？
4. 有没有一些推荐的设置？

十分感谢解答。(这些完全可以做一个FAQ了。

**Comment by zyh001** [comment]
@LennoC 你好，该脚本安装v2ray包的脚本就是采用的官方脚本，所以会直接覆盖的

**Comment by LennoC** [comment]
@zyh001 感谢回复。我选择了mck BT伪装，现在发现iOS端的Shadowrocket和Shadowray没办法正常使用。请问需要做什么配置吗？

**Comment by zyh001** [comment]
@LennoC iOS下shadowrocket目前对于v2ray的支持还有问题.
关于推荐的配置，你可以参考[官网推荐配置](https://www.v2ray.com/chapter_05/00_config/)

**Comment by LennoC** [comment]
@zyh001 已解决。iOS的工具目前不支持mkcp. 换了普通http伪装。
提一些改进建议：

**Comment by zyh001** [comment]
@LennoC 谢建议，可以考虑加入多端口功能
