### ISSUE TITLE
建议能够监听的自定义IP地址

### ISSUE THREAD

**Issue by 1715173329** [FunctionClub/V2ray.Fun#7]
如题，部分使用Caddy/Nginx做反代的用户就不需要再监听公网IP了，直接127.0.0.1就可以了；
另外面板SSL建议强制要求绑定域名签发Let's encrypt的证书。

**Comment by zyh001** [comment]
@1715173329 您好，您可以自行修改文件`app.py`的第`230`和`232`行，将`0.0.0.0`修改为`127.0.0.1`即可。若您对域名绑定SSL证书有需求的话，您可以尝试使用[https://git.fdos.me/v2ray/V2ray.Fun](https://git.fdos.me/v2ray/V2ray.Fun)所提供的版本，支持自签证书，并配置反代，但可能会出现一些问题。感谢您对项目的支持

**Comment by 1715173329** [comment]
好的，谢谢
