### ISSUE TITLE
请问在什么地方设置用户名和密码呢？

### ISSUE THREAD

**Issue by laoz77** [FunctionClub/V2ray.Fun#8]
谢谢开发者的工作！已经顺利运行，但是没看到在那里设置用户名和密码，能在什么地方设置一下呢？

**Comment by zyh001** [comment]
@laoz77 目前项目处于开发状态，暂不完善，请手动修改文件`panel.config`，来修改帐号名和密码

**Comment by ghost** [comment]
@laoz77 直接输入 v2ray 然后回车，就可以了。
