### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by updater1234** [FunctionClub/v2ray.fun#8]
你好，请问一下这个脚本是管理本地端还是服务端？如果是服务端的话，为什么还有加密方式，不是说本地端配置了不就行吗？

**Comment by tefiszx** [comment]
是运行在服务端的。加密方式是导出客户端配置所用的。

**Comment by updater1234** [comment]
ok，谢谢。那为什么我用客户端配置文件时，监听ip是0.0.0.0 ，不应该是127.0.0.1吗？

**Comment by zyh001** [comment]
@updater1234 这里的0.0.0.0表示的是本机所有IP，具体差异请自行上网搜索，此次不做赘述!
