### ISSUE TITLE
nstall.sh: line 125: supervisord: command not found

### ISSUE THREAD

**Issue by logdns** [FunctionClub/V2ray.Fun#9]
Cloning into 'V2ray.Fun'...
remote: Counting objects: 238, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 238 (delta 0), reused 0 (delta 0), pack-reused 235
Receiving objects: 100% (238/238), 2.54 MiB | 2.16 MiB/s, done.
Resolving deltas: 100% (108/108), done.
Checking connectivity... done.
Collecting pip
  Downloading https://files.pythonhosted.org/packages/0f/74/ecd13431bcc456ed390b44c8a6e917c1820365cbebcb6a8974d1cd045ab4/pip-10.0.1-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 987kB/s
Installing collected packages: pip
  Found existing installation: pip 8.1.1
    Not uninstalling pip at /usr/lib/python2.7/dist-packages, outside environment /usr
Successfully installed pip-10.0.1
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main
install.sh: line 72: echo_supervisord_conf: command not found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    14    0    14    0     0     49      0 --:--:-- --:--:-- --:--:--    49
请输入默认用户名[默认admin]： admin
请输入默认登录密码[默认admin]： admin
请输入监听端口号[默认5000]： 5000
install.sh: line 125: supervisord: command not found
安装成功！
面板登录地址：http://52.192.14.255:5000
默认用户名：admin
默认密码：admin

输入 v2ray 并回车可以手动管理网页面板相关功能

**Comment by zyh001** [comment]
@logdns 您好，我无法复现你的问题，但您可以尝试修改文件`/usr/bin/pip`，将

`from pip import main
if __name__ == '__main__':
    sys.exit(main())`
修改为

`from pip import __main__
if __name__ == '__main__':
    sys.exit(__main__._main())`
并重新执行安装脚本来解决。感谢您对项目的支持！
