### ISSUE TITLE
How to uninstall it

### ISSUE THREAD

**Issue by iuli-moe** [FunctionClub/v2ray.fun#9]
RT.

**Comment by zyh001** [comment]
@iuli-moe 
If you want to uninstall this script, you can run this:
`rm -f /usr/local/bin/v2ray`
`rm -rf /usr/local/v2ray.fun`
If you want to uninstall V2ray, please run the instructions:
`service v2ray stop`
`update-rc.d -f v2ray remove`
`rm -rf /etc/v2ray`
`rm -rf /usr/bin/v2ray`
`rm -rf /var/log/v2ray`
That's all.

**Comment by logdns** [comment]
修改后一样   我是 aws 
Reading package lists... Done
Building dependency tree
Reading state information... Done
unzip is already the newest version (6.0-20ubuntu1).
socat is already the newest version (1.7.3.1-1).
ca-certificates is already the newest version (20170717~16.04.1).
curl is already the newest version (7.47.0-1ubuntu2.8).
git is already the newest version (1:2.7.4-0ubuntu1.3).
openssl is already the newest version (1.0.2g-1ubuntu4.12).
python is already the newest version (2.7.12-1~16.04).
wget is already the newest version (1.17.1-1ubuntu1.4).
python-pip is already the newest version (8.1.1-2ubuntu0.4).
supervisor is already the newest version (3.2.0-2ubuntu0.1).
0 upgraded, 0 newly installed, 0 to remove and 61 not upgraded.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   705  100   705    0     0   1348      0 --:--:-- --:--:-- --:--:--  1350
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  164k  100  164k    0     0   583k      0 --:--:-- --:--:-- --:--:--  583k
[Thu May 17 14:40:23 UTC 2018] Installing from online archive.
[Thu May 17 14:40:23 UTC 2018] Downloading https://github.com/Neilpang/acme.sh/archive/master.tar.gz
[Thu May 17 14:40:25 UTC 2018] Extracting master.tar.gz
[Thu May 17 14:40:25 UTC 2018] Installing to /root/.acme.sh
[Thu May 17 14:40:25 UTC 2018] Installed to /root/.acme.sh/acme.sh
[Thu May 17 14:40:25 UTC 2018] Installing alias to '/root/.bashrc'
[Thu May 17 14:40:25 UTC 2018] OK, Close and reopen your terminal to start using acme.sh
[Thu May 17 14:40:25 UTC 2018] Installing cron job
39 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null
[Thu May 17 14:40:25 UTC 2018] Good, bash is found, so change the shebang to use bash as preferred.
[Thu May 17 14:40:25 UTC 2018] OK
[Thu May 17 14:40:25 UTC 2018] Install success!
Latest version v3.21 is already installed.
fatal: destination path 'V2ray.Fun' already exists and is not an empty directory.
  File "/usr/bin/pip", line 9
    from pip import __main__ if __name__ == '__main__': sys.exit(__main__._main())
                              ^
SyntaxError: invalid syntax
  File "/usr/bin/pip", line 9
    from pip import __main__ if __name__ == '__main__': sys.exit(__main__._main())
                              ^
SyntaxError: invalid syntax
  File "/usr/bin/pip", line 9
    from pip import __main__ if __name__ == '__main__': sys.exit(__main__._main())
                              ^
SyntaxError: invalid syntax

^CTraceback (most recent call last):
  File "init.py", line 12, in <module>
    data['ip'] = Config_Generator.getip()
  File "/usr/local/V2ray.Fun/Config_Generator.py", line 9, in getip
    myip = urllib2.urlopen('http://members.3322.org/dyndns/getip').read()
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1136, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
KeyboardInterrupt
mkdir: cannot create directory â€˜/etc/supervisorâ€™: File exists
mkdir: cannot create directory â€˜/etc/supervisor/config.dâ€™: File exists
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

**Comment by zyh001** [comment]
@logdns 若您使用了非纯净系统，您可以尝试重装系统，随后修改安装文件`install.sh`，删除掉第56行的`pip install --upgrade pip`，之后重新执行即可
